import {
  Box,
  Container,
  SimpleGrid,
  useDisclosure,
  useMediaQuery,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useGetMangaListQuery, Manga } from '../generated/graphql';
import { MangaFiltering, BottomSheet, VerticalCard } from '../components';

const Browse: NextPage = () => {
  const [isLargerThan803] = useMediaQuery('(min-width: 803px)');
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [result] = useGetMangaListQuery();

  return (
    <div>
      <Head>
        <title>Dango Manga - Browse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container paddingTop={isLargerThan803 ? 12 : 10} maxW="container.xl">
          <MangaFiltering
            search={(value) => console.log(value)}
            selectCategory={(option) => console.log(option)}
            selectFormat={(option) => console.log(option)}
            selectStatus={(option) => console.log(option)}
            openBottomSheet={onOpen}
          />
          <BottomSheet
            header="Hello"
            borderRadius={22}
            isOpen={isOpen}
            onClose={onClose}
            content={<Box />}
          />
          <SimpleGrid
            columns={{ sm: 2, md: 4, lg: 6 }}
            spacing={isLargerThan803 ? 10 : 8}
          >
            {result.data?.getMangaList &&
              result.data?.getMangaList.map((manga) => (
                <VerticalCard key={manga?.id} manga={manga as Manga} />
              ))}
          </SimpleGrid>
        </Container>
      </main>
    </div>
  );
};

export default Browse;
