import { Box, Container, SimpleGrid, useDisclosure } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useGetAllMangasQuery } from '../generated/graphql';
import { MangaFiltering, BottomSheet, VerticalCard } from '../components';
import { useScreen } from '../hooks';

const Browse: NextPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [result] = useGetAllMangasQuery();
  const isDesktop = useScreen();

  return (
    <div>
      <Head>
        <title>Dango Manga - Browse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container paddingTop={isDesktop ? 12 : 10} maxW="container.xl">
          <MangaFiltering
            search={(value) => console.log(value)}
            selectCategory={(option) => console.log(option)}
            selectFormat={(option) => console.log(option)}
            selectStatus={(option) => console.log(option)}
            openBottomSheet={onOpen}
          />
          <BottomSheet
            header="Hello"
            borderRadius={22}
            isOpen={isOpen}
            onClose={onClose}
            content={<Box />}
          />
          <SimpleGrid
            columns={{ sm: 2, md: 3, lg: 5 }}
            spacing={isDesktop ? 6 : 4}
          >
            {result.data?.list &&
              result.data?.list.map((manga) => (
                <VerticalCard
                  key={manga?.ID}
                  manga={{
                    ID: manga?.ID,
                    thumbnail: manga?.thumbnail,
                    name: manga?.name,
                  }}
                />
              ))}
          </SimpleGrid>
        </Container>
      </main>
    </div>
  );
};

export default Browse;
