import { Container, SimpleGrid, useMediaQuery } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useGetMangaListQuery, Manga } from '../generated/graphql';
import { HorizontalCard } from '../components';

const Popular: NextPage = () => {
  const [isLargerThan803] = useMediaQuery('(min-width: 803px)');
  const [result] = useGetMangaListQuery();

  return (
    <div>
      <Head>
        <title>Dango Manga - Popular</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container paddingTop={isLargerThan803 ? 20 : 10} maxW="container.xl">
          <SimpleGrid
            columns={{ sm: 1, md: 2 }}
            spacing={isLargerThan803 ? 10 : 6}
          >
            {result.data?.getMangaList &&
              result.data?.getMangaList.map((manga) => (
                <HorizontalCard key={manga?.id} manga={manga as Manga} />
              ))}
          </SimpleGrid>
        </Container>
      </main>
    </div>
  );
};

export default Popular;
